### ISSUE TITLE
Install Progress Map plugin on croakey.com site

### ISSUE THREAD

**Issue by henare** [croakey/website#6]
And send the plugin to @henare so he can test it locally.

**Comment by mozzyAU** [comment]
Pricing table for Google Maps: https://cloud.google.com/maps-platform/pricing/sheet/ We have $200 credit per month.

**Comment by henare** [comment]
We installed Progress Map locally and tested it. While we're happy with the front-end it generates for people visiting the site the backend for editors is a bit difficult to use.

Items on the map are Posts. These need to be hidden from the main display on the site and on the feed (not to mention from other plugins as in #7). This isn't a show-stopper but it's a bit clunky. I think I expected it to use it's own custom posts that remained hidden from the rest of WordPress.

AFAICT there's no editor to draw polylines, e.g. for drawing the walking path of a CroakeyGO. To make these you need to manually put the geocordinates of all the points into a text field. This is fiddly for a technical user and very difficult for a non-technical editor.

Once you've made maps using this plugin there's no clean representation of that map, e.g. a simple export. Again, this isn't a show-stopper but it's a red flag that we're building so much extra smarts into our already complex WordPress site.

---

So we revisited options for creating map-based stories. I especially was looking for existing solutions based on open source or open standards so we're not locked into proprietary products and so we have the most options should we choose to develop the solution further.

[Story Maps](https://storymaps.arcgis.com/en/) looks like the right kind of thing but needs the commercial ArcGIS. There's a free tier but you're locked in to them.

[StoryMapJS](https://storymap.knightlab.com/) looks great and is even by Knight Lab, which is specifically about journalism. This seems pretty opinionated about how the story works but it's a way we already envisaged our CroakeyGO stories working. The show-stopper for us is that it doesn't currently support collaborative editing so we've got no way to edit each other's StoryMaps! :disappointed: 

[uMap](https://umap.openstreetmap.fr/en/) is an open source project by Open Street Map to create maps with layers and embed them on a site. This sounds a bit generic for what we want but there are some interesting story-like features built-in. The online editor is comprehensive but understandable. You can export and import content and sharing a link to edit each other's maps is simple.

We've decided to try using uMaps instead for our first map.
