### ISSUE TITLE
Need to write a WP filter function for Apple News plugin to remove MappingCroakeyGo category from Apple News feed

### ISSUE THREAD

**Issue by mozzyAU** [croakey/website#7]

**Comment by mozzyAU** [comment]
ATM we cant publish any Mapping Croakey Go posts, as they are automatically posted to Apple News

**Comment by henare** [comment]
We've decided [not to use](https://github.com/croakey/website/issues/6#issuecomment-418581088) this WordPress plugin for now so this shouldn't be an issue.
